---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smith
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smith
    spec:
      containers:
      - name: smith
        image: "atlassianlabs/smith:4fddcf8-race"
        imagePullPolicy: Always
        args:
        - '-service-catalog-url'
        - 'http://catalog-catalog-apiserver.catalog'
