---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: smith
rules:

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch

- apiGroups:
  - smith.atlassian.com
  resources:
  - bundles
  verbs:
  - list
  - watch
  - update # need to be able to update finalizers

- apiGroups:
  - smith.atlassian.com
  resources:
  - bundles/status
  verbs:
  - update

- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - serviceaccounts
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - servicebindings
  - serviceinstances
  verbs:
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: smith
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smith
subjects:
- kind: ServiceAccount
  name: smith
  namespace: <your namespace>
