---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: smith-cluster-role
rules:

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole # cluster wide role but it is bound only in a specific namespace (or multiple)
metadata:
  name: smith-namespaced-role
rules:

- apiGroups:
  - smith.atlassian.com
  resources:
  - bundles
  verbs:
  - list
  - watch
  - create
  - update

- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - settings.k8s.io
  resources:
  - podpresets
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - create
  - update
  - delete

- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - servicebindings
  - serviceinstances
  verbs:
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: smith-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smith-cluster-role
subjects:
- kind: ServiceAccount
  name: smith
  namespace: <your namespace>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: smith-namespaced-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smith-namespaced-role
subjects:
- kind: ServiceAccount
  name: smith
