apiVersion: apps/v1
kind: Deployment
metadata:
  name: smith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smith
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: smith
    spec:
      serviceAccountName: smith
      containers:
      - name: smith
        image: "atlassianlabs/smith:0.0.X-XXXX"
#        args:
#        - '-namespace'
#        - "<your namespace>"
