// +build !ignore_autogenerated

// Generated file, do not modify manually!

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Sleeper).DeepCopyInto(out.(*Sleeper))
			return nil
		}, InType: reflect.TypeOf(&Sleeper{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SleeperList).DeepCopyInto(out.(*SleeperList))
			return nil
		}, InType: reflect.TypeOf(&SleeperList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SleeperSpec).DeepCopyInto(out.(*SleeperSpec))
			return nil
		}, InType: reflect.TypeOf(&SleeperSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SleeperStatus).DeepCopyInto(out.(*SleeperStatus))
			return nil
		}, InType: reflect.TypeOf(&SleeperStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sleeper) DeepCopyInto(out *Sleeper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sleeper.
func (in *Sleeper) DeepCopy() *Sleeper {
	if in == nil {
		return nil
	}
	out := new(Sleeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sleeper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleeperList) DeepCopyInto(out *SleeperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sleeper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleeperList.
func (in *SleeperList) DeepCopy() *SleeperList {
	if in == nil {
		return nil
	}
	out := new(SleeperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SleeperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleeperSpec) DeepCopyInto(out *SleeperSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleeperSpec.
func (in *SleeperSpec) DeepCopy() *SleeperSpec {
	if in == nil {
		return nil
	}
	out := new(SleeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleeperStatus) DeepCopyInto(out *SleeperStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleeperStatus.
func (in *SleeperStatus) DeepCopy() *SleeperStatus {
	if in == nil {
		return nil
	}
	out := new(SleeperStatus)
	in.DeepCopyInto(out)
	return out
}
